In Lab : The relation from a possible “pre-admission grade” (𝑥𝑖) to “admission to a group of universities” (𝑦𝑖) for a particular student is given by the discrete fuzzy relation:

P(𝑥𝑖,𝑖)=[[0.6,0.6,0.8,0.9]
[0.1,0.2,0.9,0.8]
[0.9,0.3,0.4,0.8]
[0.9,0.8,0.1,0.2]]

The relation from a possible “admission to a university” (𝑦𝑖) to possible “completion time” (𝑧𝑘) of degree is given by the discrete relation:
Q(𝑥𝑖,𝑖)=[[0.1,0.2,0.7,0.9]
[1.1, 0.4, 0.6]
[0.0, 0.5, 0.9]
[0.91, 0.8, 0.2]]
Write a program to find the suitable relation R(𝑥𝑖,𝑘)that relates possible pre-admission grade(𝑥𝑖)to possible completion time(𝑧𝑘)of degree. Use both max-min composition and max-dot compositions


In [ ]:
import numpy as np
def max_min_composition(P, Q):
    n = len(P)
    m = len(Q[0])
    R = np.zeros((n, m))
    for i in range(n):
        for k in range(m):
            R[i, k] = np.max(np.minimum(P[i, :], Q[:, k]))
    return R

In [ ]:
def max_dot_composition(P, Q):
    n = len(P)
    m = len(Q[0])
    R = np.zeros((n, m))
    for i in range(n):
        for k in range(m):
            R[i, k] = np.max(P[i, :] * Q[:, k])
    return R


In [ ]:
P = np.array([[0.6, 0.6, 0.8, 0.9],
              [0.1, 0.2, 0.9, 0.8],
              [0.9, 0.3, 0.4, 0.8],
              [0.9, 0.8, 0.1, 0.2]])

Q = np.array([[0.1, 0.2, 0.7, 0.9],
              [1.1, 0.4, 0.6, 0.0],
              [0.0, 0.5, 0.9, 0.0],
              [0.9, 1.0, 0.8, 0.2]])
# Max-min composition
R_max_dot = max_dot_composition(P, Q)
print("Max-dot Composition (R_max_dot):")
print(R_max_dot)

Max-dot Composition (R_max_dot):
[[0.81 0.9  0.72 0.54]
 [0.72 0.8  0.81 0.16]
 [0.72 0.8  0.64 0.81]
 [0.88 0.32 0.63 0.81]]


In [ ]:
# Max-dot composition
R_max_dot = max_dot_composition(P, Q)
print("Max-dot Composition (R_max_dot):")
print(R_max_dot)

Max-dot Composition (R_max_dot):
[[0.81 0.9  0.72 0.54]
 [0.72 0.8  0.81 0.16]
 [0.72 0.8  0.64 0.81]
 [0.88 0.32 0.63 0.81]]


Post lab : Write a program that performs the set operations on two matrices a = FuzzySet({('x1', 0.5), ('x2', 0.7), ('x3', 0.0)}) b = FuzzySet({('x1', 0.8), ('x2', 0.2), ('x3', 1.0)}) union and intersection.

In [1]:
class FuzzySet:
    def __init__(self, elements):
        self.elements = dict(elements)

    def union(self, other):
        union_elements = dict(self.elements)
        for key, value in other.elements.items():
            if key in union_elements:
                union_elements[key] = max(union_elements[key], value)
            else:
                union_elements[key] = value
        return FuzzySet(union_elements.items())

    def intersection(self, other):
        intersection_elements = {}
        for key, value in self.elements.items():
            if key in other.elements:
                intersection_elements[key] = min(value, other.elements[key])
        return FuzzySet(intersection_elements.items())

    def __str__(self):
        return str(self.elements)


# Create the fuzzy sets
a = FuzzySet({('x1', 0.5), ('x2', 0.7), ('x3', 0.0)})
b = FuzzySet({('x1', 0.8), ('x2', 0.2), ('x3', 1.0)})

# Perform set operations
union_result = a.union(b)
intersection_result = a.intersection(b)

# Print the results
print("Union:", union_result)
print("Intersection:", intersection_result)

Union: {'x1': 0.8, 'x2': 0.7, 'x3': 1.0}
Intersection: {'x1': 0.5, 'x2': 0.2, 'x3': 0.0}
